name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # roz raat 12 baje (UTC) chalega
  workflow_dispatch:

permissions:
  contents: write   # 👈 push karne ke liye zaroori

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          USERNAME: Abdulqadir000
          AUTO_PUSH: false

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "⏰ auto-update GitHub summary cards" || echo "No changes to commit"
          git push
